name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release_draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # build_release:
  #   runs-on: windows-latest
  #   needs: release_draft
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         cache: 'yarn'

  #     - name: Install dependencies
  #       run: yarn

  #     - name: Build vite
  #       run: yarn build:vite

  #     - name: Build electron
  #       run: yarn run electron-builder
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
